export type { BindCookieResult, StoredCookieData } from '@src/model/mihoyo/account';
export type { GameRoleInfo, MysApiResponse } from '@src/model/mihoyo/mysApi';
export type { QueryResult } from '@src/model/mihoyo/query';
export type { BbsSignResult, SignResult, SignRoleResult } from '@src/model/mihoyo/sign';
export type { BindStokenResult, QrCodeStatus, QrSession, StokenData } from '@src/model/mihoyo/stoken';
export type { MihoyoGame, MihoyoRegionProfile, MihoyoRegionType } from '@src/model/mihoyo/types';
export type { MihoyoContext } from '@src/model/mw.js';
export { resolveGame } from '@src/model/mw.js';
export { resolveMihoyoRegion } from '@src/model/mihoyo/region';
export { addUserUid, bindUserCookie, deleteUserCookie, getUserCookie, getUserMainUid, getUserUids, removeUserUid } from '@src/model/mihoyo/account';
export { bindStoken, buildStokenCookie, deleteUserStoken, getUserStoken, saveUserStoken } from '@src/model/mihoyo/stoken';
export { performBbsSign, performGameSign, resolveSignGameKey } from '@src/model/mihoyo/sign';
export { queryMihoyoApi } from '@src/model/mihoyo/query';
export { fetchGameRoles, fetchUserFullInfo, mysApiFetch } from '@src/model/mihoyo/mysApi';
declare const _default: import("alemonjs").DefineChildrenValue;
export default _default;
