export declare const ELEMENT_ICONS: Record<string, string>;
export declare const ELEMENT_ICONS_EN: Record<string, string>;
export declare const UI_ICONS: {
    readonly abyss: string;
    readonly ledger: string;
    readonly paimon: string;
    readonly role: string;
    readonly sign: string;
    readonly team: string;
    readonly weapon: string;
    readonly resin: string;
    readonly primogem: string;
    readonly starglitter: string;
    readonly fate: string;
    readonly miyoushe: string;
    readonly help: string;
    readonly bind: string;
    readonly record: string;
    readonly stats: string;
    readonly guide: string;
    readonly checkin: string;
    readonly tcg: string;
};
export declare const BG_IMAGES: {
    readonly bg: string;
    readonly bg3: string;
    readonly bg4: string;
    readonly bg5: string;
    readonly bg105: string;
    readonly fill: string;
    readonly genshinLogo: string;
};
export declare const REGION_ICONS: Record<string, string>;
